$primary_paletteKeyColor = 9600FA
$secondary_paletteKeyColor = 9600FA
$tertiary_paletteKeyColor = B970FF
$neutral_paletteKeyColor = 000000
$neutral_variant_paletteKeyColor = 0D0D12
$background = 000000
$onBackground = F2F2F7
$surface = 000000
$surfaceDim = 000000
$surfaceBright = 08080A
$surfaceContainerLowest = 000000
$surfaceContainerLow = 000000
$surfaceContainer = 000000
$surfaceContainerHigh = 08080A
$surfaceContainerHighest = 101014
$onSurface = F2F2F7
$surfaceVariant = 08080A
$onSurfaceVariant = C9C9D4
$inverseSurface = 121218
$inverseOnSurface = D7D7DF
$outline = 7A7A85
$outlineVariant = 1A1A22
$shadow = 000000
$scrim = 000000
$surfaceTint = 9600FA
$primary = 9600FA
$onPrimary = F7F2FF
$primaryContainer = 1A002D
$onPrimaryContainer = DDB6FF
$inversePrimary = B970FF
$secondary = 9600FA
$onSecondary = F7F2FF
$secondaryContainer = 1A002D
$onSecondaryContainer = DDB6FF
$tertiary = B970FF
$onTertiary = 15001F
$tertiaryContainer = 25003D
$onTertiaryContainer = E8D5FF
$error = C66E73
$onError = F5F4F6
$errorContainer = 893034
$onErrorContainer = F5F4F6
$primaryFixed = 9600FA
$primaryFixedDim = 7A00CC
$onPrimaryFixed = F7F2FF
$onPrimaryFixedVariant = E8D5FF
$secondaryFixed = 9600FA
$secondaryFixedDim = 7A00CC
$onSecondaryFixed = F7F2FF
$onSecondaryFixedVariant = E8D5FF
$tertiaryFixed = B970FF
$tertiaryFixedDim = 9600FA
$onTertiaryFixed = F7F2FF
$onTertiaryFixedVariant = E8D5FF
$term0 = 2B2B2B
$term1 = 9600FA
$term2 = B970FF
$term3 = D59CFF
$term4 = 7A00CC
$term5 = C56EFF
$term6 = A94DFF
$term7 = E6E6E6
$term8 = 7F7F7F
$term9 = C56EFF
$term10 = 9600FA
$term11 = E8D5FF
$term12 = 8F5BFF
$term13 = D59CFF
$term14 = B970FF
$term15 = FFFFFF
$rosewater = F4E8FF
$flamingo = E9D2FF
$pink = D59CFF
$mauve = 9600FA
$red = FF7A9B
$maroon = D58BFF
$peach = F2A65A
$yellow = F6D365
$green = A96BFF
$teal = B970FF
$sky = C89DFF
$sapphire = 8F5BFF
$blue = 6E3BFF
$lavender = DDB6FF
$klink = 9600FA
$klinkSelection = 9600FA
$kvisited = B970FF
$kvisitedSelection = B970FF
$knegative = FF7A9B
$knegativeSelection = FF7A9B
$kneutral = F6D365
$kneutralSelection = F6D365
$kpositive = A96BFF
$kpositiveSelection = A96BFF
$text = F2F2F7
$subtext1 = C9C9D4
$subtext0 = 9999A6
$overlay2 = 777785
$overlay1 = 60606D
$overlay0 = 494954
$surface2 = 2A2A31
$surface1 = 1B1B22
$surface0 = 101015
$base = 000000
$mantle = 000000
$crust = 000000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
