action_alias launch_tab launch --type=tab --cwd=current
map f1 launch --type=tab --title=yay --cwd=current fish -c 'yay; echo ; echo "Job complete, consider revision" ; echo ; echo "Press any key to close."; read -n 1 -P ""'
map f2 launch --type=tab --title=pacsea --cwd=current fish -c "pacsea"
map f3 launch --type=overlay --cwd=current "/home/fayelia/Programs/Launcher/launcher.sh"

map f5 load_config_file
map f6 launch_tab "nano /home/fayelia/.config/kitty/kitty.conf"
font_size 16

allow_remote_control yes
shell fish
cursor_shape beam
cursor_blink_interval 0.25
cursor_trail 4
kitty_mod ctrl
tab_bar_style slant
bell_on_tab "[!] "
enable_audio_bell no
bell_path /home/fayelia/.config/kitty/ui.wav
command_on_bell pw-play /home/fayelia/.config/kitty/ui.wav
visual_bell_duration 0.15
window_margin_width 2
window_padding_width 8
confirm_os_window_close 0 count-background

# Switch to tab 1–9 with Ctrl+number
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Move between splits (windows)
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right

# BEGIN_KITTY_THEME
# pink lavender
foreground                      #9600fa
background                      #000000
selection_foreground            #000000
selection_background            #ffffff

cursor                          #9600fa
cursor_text_color               #9600fa
url_color                       #ffd3ec

active_border_color             #9600fa
inactive_border_color           #37005c
bell_border_color               #9600fa
visual_bell_color               #37005c

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_foreground           #000
active_tab_background           #9600fa
inactive_tab_foreground         #9600fa
inactive_tab_background         #000
tab_bar_background              none
tab_bar_margin_color            none
tab_activity_symbol 		"[!]"

mark1_foreground #0c0611
mark1_background #98d3cb
mark2_foreground #0c0611
mark2_background #f2dcd3
mark3_foreground #0c0611
mark3_background #f274bc

#: white
color7  #dab2cc
color15 #eed8e5

#: You can set the remaining 240 colors as color16 to color255.

# END_KITTY_THEME


# BEGIN_KITTY_FONTS
#font_family      family="MesloLGS NF"
font_family 	 family="Hack"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

scrollback_lines 1000
enable_line_wrapping yes
