background = 0xFF000000
base = 0xFF09050F
alternate_base = 0xFF12081C

text = 0xFFECE7FF
bright_text = 0xFFFFFFFF

accent = 0xFF9600FA
accent_secondary = 0xFF9F38FF

# Optional typography
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

# Optional rounding
rounding_large = 0
rounding_small = 0
