listener {
    timeout = 180
    on-timeout = notify-send "AFK" "3 minutes have passed." -i system-suspend-uninhibited
}

listener {
    timeout = 300
    on-timeout = notify-send "AFK" "5 minutes have passed." -i system-suspend-uninhibited
}

listener {
    timeout = 540
    on-timeout = notify-send "AFK" "9 minutes have passed. \nLocking screen in 1 minute." -i system-suspend-uninhibited
}

listener {
    timeout = 600 # 10min
    on-timeout = hyprctl dispatch 'hl.dsp.global("quickshell:lockscreen")'
}

listener {
    timeout = 3600 # 1hours
    on-timeout = systemctl suspend
}
