wallpaper {
    monitor = DP-1
    path = /home/fayelia/Personal/Pictures/Wallpapers/Particles.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/fayelia/Personal/Pictures/Wallpapers/Moon.jpg
    fit_mode = cover
}
    splash = false
