hl.monitor({ output = "HDMI-A-1", disabled = true, mode = "3840x2160@60", position = "0x-1080", scale = "2" })
hl.monitor({ output = "DP-1", disabled = false })
hl.monitor({ output = "DP-2", disabled = true })
