[custom]
accounts\storage-whats\css\disabled_files=@Invalid()
accounts\storage-whats\css\enabled=true
accounts\storage-whats\css\preview_map=@Variant(\0\0\0\b\0\0\0\0)
accounts\storage-whats\inherit=true
accounts\storage-whats\js\enabled=false
global\css\disabled_files=@Invalid()
global\css\enabled=true
global\css\preview_map=@Variant(\0\0\0\b\0\0\0\0)
global\js\enabled=false

[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\ag\0\0\x3\xe5\0\0\0\0\0\0\0\0\0\0\ag\0\0\x4\x1f\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\ag\0\0\x3\xe5)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\ah\0\0\x3\xe6\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=true
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
initial_setup_completed=true
last_environment=local
version=2

[performance]
js_memory_limit_index=3

[permissions]
auto_grant\camera=true
auto_grant\microphone=true
auto_grant\screen_contents=false

[privacy]
webrtc_shield=false

[system]
confirm_on_close=false
csr=false
csr_show_maximize_button=false
csr_show_minimize_button=false
download_path=/home/fayelia/Downloads
interface_language=system
menubar=false
notificationCounter=true
quit_in_close=false
scale=100
sidebar=false
spellCheckers=false
start_background=false
start_system=false
theme=dark
tray_icon=true
tray_theme=symbolic_light
wayland=true

[web]
scroll_animator=false

[website]
open_page=false
